baseURL = "https://your-site-url.com/"
languageCode = "en-us"
title = "Your Site Title"
theme = "your-theme-name"
enableRobotsTXT = true

[params]
  description = "Your site description"
  author = "Your Name"
  github = "https://github.com/your-username/your-repo"
  twitter = "https://twitter.com/your-twitter-handle"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
